services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend