services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=portal_pji_project

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: portal_pji_project
    ports:
      - "3306:3306"